### ISSUE TITLE
Missing colours

### ISSUE THREAD

**Issue by adrianblynch** [codepo8/css-colour-names#1]
I was asked to find lime green and it wasn't there!

That's 60 seconds I'll never get back :disappointed:

**Comment by codepo8** [comment]
Will check but I can't think of a way that can happen. Next time press ? -
it is a cheat mode showing you the right swab

**Comment by owenDods** [comment]
<img width="1369" alt="screen shot 2015-10-14 at 16 47 33" src="https://cloud.githubusercontent.com/assets/9574149/10489080/81d08e1e-7293-11e5-851d-0c578a5df373.png">

Can confirm - no "STEELBLUE". And pressing ? just threw errors to the console.

**Comment by codepo8** [comment]
Fixed the random function to be in the correct parameters. Sorry about that.
