### ISSUE TITLE
LIGHTSLATEGRAY is not displayed

### ISSUE THREAD

**Issue by zeke** [codepo8/css-colour-names#2]
Howdy. I like this thing, but I got stuck.

I clicked every single dot. Not one of them is LIGHTSLATEGRAY.

<img width="706" alt="screen shot 2015-10-14 at 2 26 39 pm" src="https://cloud.githubusercontent.com/assets/2289/10495090/a347ada2-727f-11e5-8cdc-326dfaa7c667.png">

**Comment by codepo8** [comment]
Sorry that was a bug, fixed now :)

**Comment by zeke** [comment]
:cake:
